cask "pgt" do
  version "0.0.37"
  sha256 "72adcc81809a610377ceacb5372905a7f57791d81b60243040a0748691aa39c7"

  url "https://github.com/evoja-brew/homebrew-tap/releases/download/pgt/#{version.sub('.', '/')}/pgt-macos-universal.tar.gz"
  name "pgt"
  desc "CLI tools for pgt"
  homepage "https://github.com/evoja-brew/homebrew-tap"

  binary "pgt"
  binary "pgt-amend"
  binary "pgt-apply-meta"
  binary "pgt-cherrypick"
  binary "pgt-collapse-events"
  binary "pgt-collapse-timestamp"
  binary "pgt-dilate"
  binary "pgt-log"
  binary "pgt-moved-code"
  binary "pgt-moved-files"
  binary "pgt-sort"
  binary "pgt-split"
  binary "pgt-tah"
  binary "pgt-tah-cp"
  binary "pgt-tah-isolate"
  binary "pgt-tah-mv"
  binary "pgt-tah-rebase"
  binary "pgt-tah-rm"
  binary "pgt-tah-unrename"
end
