cask "pgt" do
  version "0.0.39"
  sha256 "ffdfe693cca530dba18cfc12ccb3659d9977122a48167a5df7af3f38cf384bc3"

  url "https://github.com/evoja-brew/homebrew-tap/releases/download/pgt/#{version.sub('.', '/')}/pgt-macos-universal.tar.gz"
  name "pgt"
  desc "CLI tools for pgt"
  homepage "https://github.com/evoja-brew/homebrew-tap"

  binary "pgt"
  binary "pgt-amend"
  binary "pgt-apply-meta"
  binary "pgt-cherrypick"
  binary "pgt-collapse-events"
  binary "pgt-collapse-timestamp"
  binary "pgt-dilate"
  binary "pgt-log"
  binary "pgt-moved-code"
  binary "pgt-moved-files"
  binary "pgt-sort"
  binary "pgt-split"
  binary "pgt-tah"
  binary "pgt-tah-cp"
  binary "pgt-tah-isolate"
  binary "pgt-tah-mv"
  binary "pgt-tah-rebase"
  binary "pgt-tah-rm"
  binary "pgt-tah-unrename"
end
